name: seshly
description: "Seshly is a cross-campus academic platform designed to help students learn smarter, collaborate better, and access academic support instantly. Built with Flutter and Firebase, Seshly combines AI-powered learning tools, real-time collaboration, a tutor marketplace, and a student community — all in one app."

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # ----------------------------
  # UI / ICONS
  # ----------------------------
  cupertino_icons: ^1.0.8

  # ----------------------------
  # FIREBASE CORE
  # ----------------------------
  firebase_core: ^3.13.0

  # ----------------------------
  # AUTHENTICATION
  # ----------------------------
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.1

  # ----------------------------
  # DATABASE
  # ----------------------------
  cloud_firestore: ^5.6.0
  cloud_functions: ^5.3.0

  # ----------------------------
  # ANALYTICS / GROWTH
  # ----------------------------
  firebase_analytics: ^11.4.0
  firebase_crashlytics: ^4.3.0

  # ----------------------------
  # STORAGE
  # ----------------------------
  firebase_storage: ^12.4.0

  # ----------------------------
  # NOTIFICATIONS
  # ----------------------------
  firebase_messaging: ^15.2.0

  # ----------------------------
  # STATE MANAGEMENT
  # ----------------------------
  provider: ^6.1.2

  # ----------------------------
  # UTILITIES
  # ----------------------------
  intl: ^0.20.1
  uuid: ^4.5.1
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.1.2
  video_player: ^2.9.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  flutter_svg: ^2.0.17
  file_picker: ^8.1.7
  crypto: ^3.0.6
  speech_to_text: ^7.0.0
  syncfusion_flutter_pdf: ^28.2.7
  syncfusion_flutter_pdfviewer: ^28.2.7
  record: ^5.1.2
  audioplayers: ^6.1.0
  cross_file: ^0.3.4+2
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.4
  flutter_webrtc: ^0.14.1
  livekit_client: ^2.4.3

dependency_overrides:
  record_windows:
    path: third_party/record_windows
  record_linux:
    path: third_party/record_linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/seshly_logo_colored.svg
    - assets/images/seshly_logo_white.svg
    - assets/images/seshly_logo_full.svg