// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOx_B7tRyt2zPGVk1RJO6UJpMgduYYUmA',
    appId: '1:620223347958:web:292b528abac958ee0140d7',
    messagingSenderId: '620223347958',
    projectId: 'seshly-9e638',
    authDomain: 'seshly-9e638.firebaseapp.com',
    storageBucket: 'seshly-9e638.firebasestorage.app',
    measurementId: 'G-JM8SPG1MGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi6UYpKAqtdJ5-MoJ_y_x1cbXRJecHeaY',
    appId: '1:620223347958:android:1029ee58c97521170140d7',
    messagingSenderId: '620223347958',
    projectId: 'seshly-9e638',
    storageBucket: 'seshly-9e638.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-vY_q0f9FiqLx60qN0OEupXxsGu2-koQ',
    appId: '1:620223347958:ios:1e73a06a0caaeb380140d7',
    messagingSenderId: '620223347958',
    projectId: 'seshly-9e638',
    storageBucket: 'seshly-9e638.firebasestorage.app',
    iosBundleId: 'com.example.seshly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-vY_q0f9FiqLx60qN0OEupXxsGu2-koQ',
    appId: '1:620223347958:ios:1e73a06a0caaeb380140d7',
    messagingSenderId: '620223347958',
    projectId: 'seshly-9e638',
    storageBucket: 'seshly-9e638.firebasestorage.app',
    iosBundleId: 'com.example.seshly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOx_B7tRyt2zPGVk1RJO6UJpMgduYYUmA',
    appId: '1:620223347958:web:cfc42c4bc47bf8240140d7',
    messagingSenderId: '620223347958',
    projectId: 'seshly-9e638',
    authDomain: 'seshly-9e638.firebaseapp.com',
    storageBucket: 'seshly-9e638.firebasestorage.app',
    measurementId: 'G-LJSJDP2Q6T',
  );
}